connect_title = '//div[@class="profile_3CiC rtl_6mEj"]'
email_field = '(//input[@id="qa-login-email-input"])[1]'
password_field = '(//input[@id="qa-login-password-input"])[1]'
connect_button = '(//button[@class="tx-link-a submit-btn_2LDW tx-link_29YD btn_1UzJ btn-yellow_2tf3 uppercase_1KUt"])[1]'
search_button = '(//button[@class="search-button_1ENs"])[1]'
search_text = '//input[@data-test="search-input"]'
greeting_text = '(//span[@class="greet_Yfio profile-button-new-menu_2voE"])[1]'
loader_screen = '//*[@id="app-root"]/div[2]/div'
search_results = '//li[@class="container_2pxt"]'
price_results = '//div[@class="row_2tcG bold_2wBM"]'
price_page = '(//div[@class="row_2tcG bold_2wBM prices-final_1R9x"])[1]'
picture_results = '//a[@class="tx-link-a imageContainer_3DnL tx-link_29YD"]'
